// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["apps/footer/show/templates", "views/_base"], function(Templates, AppView) {
  var ShowFooterView, _ref;
  return {
    ItemView: ShowFooterView = (function(_super) {
      __extends(ShowFooterView, _super);

      function ShowFooterView() {
        _ref = ShowFooterView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ShowFooterView.prototype.template = Templates.footer;

      return ShowFooterView;

    })(AppView.ItemView)
  };
});
