// Generated by CoffeeScript 1.6.3
define(["backbone", "backbone.marionette", "msgbus", "apps/load"], function(Backbone, Marionette, msgBus) {
  var app;
  app = new Marionette.Application();
  app.rootRoute = "about";
  app.authRoute = "games";
  app.addRegions({
    headerRegion: "#header-region",
    mainRegion: "#main-region",
    footerRegion: "#footer-region"
  });
  app.on("initialize:before", function(options) {
    if (options == null) {
      options = {};
    }
  });
  msgBus.reqres.setHandler("default:region", function() {
    return app.mainRegion;
  });
  msgBus.reqres.setHandler("header:region", function() {
    return app.headerRegion;
  });
  msgBus.reqres.setHandler("footer:region", function() {
    return app.footerRegion;
  });
  msgBus.reqres.setHandler("main:region", function() {
    return app.mainRegion;
  });
  app.on("initialize:after", function(options) {
    var frag;
    if (options == null) {
      options = {};
    }
    if (Backbone.history) {
      Backbone.history.start();
      return frag = Backbone.history.fragment;
    }
  });
  app.addInitializer(function(options) {
    msgBus.commands.execute("start:header:app");
    msgBus.commands.execute("start:footer:app");
    return msgBus.commands.execute("start:bills:app");
  });
  return app;
});
