// Generated by CoffeeScript 1.6.3
require.config({
  paths: {
    jquery: "../bower_components/jquery/jquery",
    backbone: "../bower_components/backbone-amd/backbone",
    underscore: "../bower_components/underscore-amd/underscore",
    "backbone.marionette": "../bower_components/backbone.marionette/lib/core/amd/backbone.marionette",
    "backbone.wreqr": "../bower_components/backbone.wreqr/lib/amd/backbone.wreqr",
    "backbone.babysitter": "../bower_components/backbone.babysitter/lib/amd/backbone.babysitter",
    "backbone.syphon": "../bower_components/backbone.syphon/lib/amd/backbone.syphon",
    obscura: "../bower_components/backbone.obscura/backbone.obscura",
    bootstrap: "vendor/bootstrap",
    royalslider: "vendor/jquery.royalslider", //royalslider.min",
    "rs.autoheight": "vendor/modules/jquery.rs.auto-height",
    "rs.active-class": "vendor/modules/jquery.rs.active-class",
    "rs.animated-blocks": "vendor/modules/jquery.rs.animated-blocks",
    d3: "../bower_components/d3/d3",
    text: "../bower_components/requirejs-text/text",
    handlebars: "../bower_components/require-handlebars-plugin/Handlebars",
    i18nprecompile: "../bower_components/require-handlebars-plugin/hbs/i18nprecompile",
    json2: "../bower_components/require-handlebars-plugin/hbs/json2",
    hbs: "../bower_components/require-handlebars-plugin/hbs"
  },
  hbs: {
    disableI18n: true
  },
  shim: {
    royalslider: {
      deps: ["jquery"]
    },
    "rs.autoheight": {
      deps:["royalslider"]
    },
    "rs.active-class": {
      deps:["royalslider"]
    },
    "rs.animated-blocks": {
      deps:["royalslider"]
    },
    bootstrap: {
      deps: ["jquery"],
      exports: "jquery"
    }
  }
});

require(["config/load", "app"], function(_config, app) {
  return app.start();
});
