// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["msgbus", "apps/header/list/views", "controller/_base", "entities/header"], function(msgBus, Views, AppController) {
  var Controller, _ref;
  return Controller = (function(_super) {
    __extends(Controller, _super);

    function Controller() {
      _ref = Controller.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Controller.prototype.initialize = function() {
      var _this = this;
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, "show", function() {
        return _this.showHeaderView();
      });
      return this.show(this.layout);
    };

    Controller.prototype.getLayoutView = function() {
      return new Views.Layout;
    };

    Controller.prototype.showHeaderView = function() {
      var view;
      view = this.getHeaderView();
      return this.layout.navRegion.show(view);
    };

    Controller.prototype.getHeaderView = function() {
      return new Views.HeaderView;
    };

    return Controller;

  })(AppController);
});
