// Generated by CoffeeScript 1.6.3
define(["hbs!apps/header/list/templates/layout", "hbs!apps/header/list/templates/header"], function(Layout, Header) {
  return {
    layout: Layout,
    header: Header
  };
});
