// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["apps/header/list/templates", "views/_base"], function(Templates, AppView) {
  var Header, ListHeaders, _ref, _ref1;
  return {
    Layout: Header = (function(_super) {
      __extends(Header, _super);

      function Header() {
        _ref = Header.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Header.prototype.template = Templates.layout;

      Header.prototype.regions = {
        navRegion: "#nav-region"
      };

      return Header;

    })(AppView.Layout),
    HeaderView: ListHeaders = (function(_super) {
      __extends(ListHeaders, _super);

      function ListHeaders() {
        _ref1 = ListHeaders.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      ListHeaders.prototype.template = Templates.header;

      return ListHeaders;

    })(AppView.ItemView)
  };
});
