// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["msgbus", "apps/mps/profile/views", "controller/_base", "backbone", "obscura", "apps/bills/app"], function(msgBus, Views, AppController, Backbone, Obscura, BillsApp) {
  var Controller, _ref;
  return Controller = (function(_super) {
    __extends(Controller, _super);

    function Controller() {
      _ref = Controller.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Controller.prototype.initialize = function(options) {
      var billsData, mpBills,
        _this = this;
      if (options == null) {
        options = {};
      }
      console.log("options: ", options);
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, "show", function() {
        _this.detailsRegion(options.mpData);
        return _this.tiledBillsRegion();
      });
      this.show(this.layout);
      console.log("@layout.billRegion", this.layout.billsRegion);
      billsData = {
        region: this.layout.billsRegion,
        mpName: options.mpData.mp,
        isMpPage: true
      };
      return mpBills = msgBus.reqres.request("get:bills:app", billsData);
    };

    Controller.prototype.detailsRegion = function(mpData) {
      var detailsView, mpModel, mpModelData;
      console.log("mpData", mpData);
      mpModelData = Backbone.Model.extend();
      mpModel = new mpModelData(mpData);
      detailsView = new Views.DetailsView({
        model: mpModel
      });
      return this.layout.detailsRegion.show(detailsView);
    };

    Controller.prototype.tiledBillsRegion = function() {};

    Controller.prototype.getLayoutView = function() {
      return new Views.Layout;
    };

    return Controller;

  })(AppController);
});
