// Generated by CoffeeScript 1.6.3
define(["hbs!apps/mps/profile/templates/layout", "hbs!apps/mps/profile/templates/details"], function(Layout, Details) {
  return {
    layout: Layout,
    details: Details
  };
});
