// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['apps/mps/profile/templates', 'views/_base', 'msgbus'], function(Templates, AppView, msgBus) {
  var DetailsView, MpsAppLayout, _ref, _ref1;
  return {
    DetailsView: DetailsView = (function(_super) {
      __extends(DetailsView, _super);

      function DetailsView() {
        _ref = DetailsView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      DetailsView.prototype.template = Templates.details;

      return DetailsView;

    })(AppView.ItemView),
    Layout: MpsAppLayout = (function(_super) {
      __extends(MpsAppLayout, _super);

      function MpsAppLayout() {
        _ref1 = MpsAppLayout.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      MpsAppLayout.prototype.template = Templates.layout;

      MpsAppLayout.prototype.regions = {
        detailsRegion: "#details-region",
        billsRegion: "#mp-bills-region"
      };

      return MpsAppLayout;

    })(AppView.Layout)
  };
});
