// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["msgbus", "apps/bills/list/views", "controller/_base", "backbone"], function(msgBus, Views, AppController, Backbone) {
  var Controller, _ref;
  return Controller = (function(_super) {
    __extends(Controller, _super);

    function Controller() {
      _ref = Controller.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Controller.prototype.initialize = function(options) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      this.entities = msgBus.reqres.request("bill:entities");
      msgBus.commands.setHandler("toggle:bills:region", function() {
        return _this.toggleBillsRegion();
      });
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, "show", function() {
        _this.searchRegion();
        return _this.slideRegion();
      });
      return this.show(this.layout);
    };

    Controller.prototype.getLayoutView = function() {
      return new Views.Layout;
    };

    Controller.prototype.slideRegion = function() {
      var sliderView;
      sliderView = this.getSliderView(this.entities);
      this.layout.billsRegion.show(sliderView);
      return sliderView.slider.updateSliderSize();
    };

    Controller.prototype.tileRegion = function() {
      var tileView;
      tileView = this.getTileView(this.entities);
      return this.layout.billsRegion.show(tileView);
    };

    Controller.prototype.toggleBillsRegion = function() {
      if (this.layout.billsRegion.currentView instanceof Views.SliderView) {
        return this.tileRegion();
      } else {
        return this.slideRegion();
      }
    };

    Controller.prototype.searchRegion = function() {
      return msgBus.commands.execute("show:search", this.layout.searchRegion);
    };

    Controller.prototype.getTileView = function(collection) {
      return new Views.TileView({
        collection: collection
      });
    };

    Controller.prototype.getSliderView = function(collection) {
      return new Views.SliderView({
        collection: collection
      });
    };

    return Controller;

  })(AppController);
});
