// Generated by CoffeeScript 1.6.3
define(["hbs!apps/bills/list/templates/layout", "hbs!apps/bills/list/templates/slider", "hbs!apps/bills/list/templates/slideItem", "hbs!apps/bills/list/templates/tile", "hbs!apps/bills/list/templates/tileItem"], function(Layout, Slider, SlideItem, Tile, TileItem) {
  return {
    layout: Layout,
    slider: Slider,
    slideItem: SlideItem,
    tile: Tile,
    tileItem: TileItem
  };
});
