// Generated by CoffeeScript 1.6.3
define(["hbs!apps/bills/list/templates/layout", "hbs!apps/bills/list/templates/slider", "hbs!apps/bills/list/templates/slideItem"], function(Layout, Slider, SlideItem) {
  return {
    layout: Layout,
    slider: Slider,
    slideItem: SlideItem
  };
});
