// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['apps/bills/list/templates', 'views/_base', 'msgbus'], function(Templates, AppView, msgBus) {
  var BillsLayout, SlideItem, SliderView, _ref, _ref1, _ref2;
  SlideItem = (function(_super) {
    __extends(SlideItem, _super);

    function SlideItem() {
      _ref = SlideItem.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SlideItem.prototype.template = Templates.slideItem;

    return SlideItem;

  })(AppView.ItemView);
  return {
    SliderView: SliderView = (function(_super) {
      __extends(SliderView, _super);

      function SliderView() {
        _ref1 = SliderView.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      SliderView.prototype.template = Templates.slider;

      SliderView.prototype.itemView = SlideItem;

      SliderView.prototype.itemViewContainer = "#panes";

      return SliderView;

    })(AppView.CompositeView),
    Layout: BillsLayout = (function(_super) {
      __extends(BillsLayout, _super);

      function BillsLayout() {
        _ref2 = BillsLayout.__super__.constructor.apply(this, arguments);
        return _ref2;
      }

      BillsLayout.prototype.template = Templates.layout;

      BillsLayout.prototype.regions = {
        searchRegion: "#search-region",
        billsRegion: "#bills-region"
      };

      return BillsLayout;

    })(AppView.Layout)
  };
});
