// Generated by CoffeeScript 1.6.3
define(["config/jquery/jquery", "config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/application", "config/backbone/sync", "entities/bills", "bootstrap"], function() {});
