// Generated by CoffeeScript 1.6.3
define(["hbs!apps/bills/search/templates/layout", "hbs!apps/bills/search/templates/input", "hbs!apps/bills/search/templates/menu", "hbs!apps/bills/search/templates/toggle"], function(Layout, Input, Menu, Toggle) {
  return {
    layout: Layout,
    input: Input,
    menu: Menu,
    toggle: Toggle
  };
});
