// Generated by CoffeeScript 1.6.3
define(["hbs!apps/bills/search/templates/layout", "hbs!apps/bills/search/templates/input", "hbs!apps/bills/search/templates/menu"], function(Layout, Input, Menu) {
  return {
    layout: Layout,
    input: Input,
    menu: Menu
  };
});
