// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['apps/bills/search/templates', 'views/_base', 'msgbus'], function(Templates, AppView, msgBus) {
  var InputView, MenuView, SearchLayout, _ref, _ref1, _ref2;
  return {
    Layout: SearchLayout = (function(_super) {
      __extends(SearchLayout, _super);

      function SearchLayout() {
        _ref = SearchLayout.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      SearchLayout.prototype.template = Templates.layout;

      SearchLayout.prototype.regions = {
        inputRegion: "#input-region",
        menuRegion: "#menu-region"
      };

      return SearchLayout;

    })(AppView.Layout),
    InputView: InputView = (function(_super) {
      __extends(InputView, _super);

      function InputView() {
        _ref1 = InputView.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      InputView.prototype.template = Templates.input;

      return InputView;

    })(AppView.ItemView),
    MenuView: MenuView = (function(_super) {
      __extends(MenuView, _super);

      function MenuView() {
        _ref2 = MenuView.__super__.constructor.apply(this, arguments);
        return _ref2;
      }

      MenuView.prototype.template = Templates.menu;

      return MenuView;

    })(AppView.ItemView)
  };
});
